### PR TITLE
Enhanced player character jump

### PR DESCRIPTION
**Pull request by fedeDeb**
Improved character jump. Some explanatory comments have been included

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@fedeDeb The jump style is great, much more like the old Mario platforms games which is what was originally intended. 

Your PR is also showing other changes like the deletion of the LEVEL_COMPLETION_SCORE variable and the mute functions. Did you mean to do that?

The new jump style really adds to the game play!

**Comment by fedeDeb** [comment]
I'm so sorry! I haven't voluntarily changed the things you have reported to me! No, I didn't want to do it, I think there was a problem because initially I did not realize that my repository was not synchronized with yours, so probably the changes went into conflict ...
The only thing I really meant to do about the audio was the control in the keyPressed function, which binds the audio to the jump when it's really about to jump and not when it's in the air.
I'm not yet a github expert, I'm at my first arms, sorry again.

I am, however, happy to have achieved what you meant for the jump!

**Comment by EdwardDunn** [comment]
@fedeDeb Its no problem, if you make sure you update your version of the repository to include any recent changes. When "m" is pressed all sounds and music should mute.

To make sure your repo is tracking the master branch use 'git remote' command

To pull recent changes use 'git pull' command.

Hope this helps!

**Comment by fedeDeb** [comment]
Ok thank you, the next time I will do this. I fixed the problem now, and explain what i've done in my corrections. Let me know!

**Comment by EdwardDunn** [comment]
@fedeDeb The jump sound is still not muting when the 'm' button is pressed. I'm not sure whether you changed this or your version of the repo is out of date, either way the following fix will work.

If you replace the if loop starting on line 56 with the following code, it should work.

	if (keysPressed[UP]) {
		if (!musicMuted) {
			jump.autoplay=true;
			jump.load();
		}
		moveUp();
	}

Once you have done this i will merge your PR. Great job!

**Comment by fedeDeb** [comment]
I understand what you want to tell me, but simply inserting that piece of code overrides my change. So now they both work :)

`if (keysPressed[UP] && playerCharacter.hitGround) { 
		moveUp(); 
		if (!musicMuted) {
			jump.autoplay=true;
			jump.load();
		}
}`

My change requires that when you press Jump, the jump sound will only be played once. I don't know if you had noticed, but first, if the character was in the air and you were repeating Jump the sound was played twice, and it did not make much sense.

**Comment by EdwardDunn** [comment]
@fedeDeb Sorry i was confused about what you were trying to do.

Your change stops the jump sound when the player is in the air for the keys, but it still occurs when you use the on screen buttons. 

Can you open up a new issue for this, I will merge your current PR as is.

A little tip for further contributions, if you want to make any extra changes open a new issue and PR separately, that way its clear exactly what you're trying to achieve with each change.

The jump style is much better, thanks for your contribution!

**Pull request merged**
