### PR TITLE
created banner

### PR DESCRIPTION
**Pull request by ShrutiArya96**
Created and added a banner to the pictures folder but not being able to place it on the html canvas

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@ShrutiArya96 Thanks for your interest, the banner looks great! To add it to the canvas you will need to create a new game component in the Game.js file. If you have a look at how the background and score board are shown this may help.

Just let me know if you need anymore help.

**Comment by EdwardDunn** [comment]
@shrutiArya96 it might actually be easier to add it to the JS_game.html. If you look at how the buttons are shown on screen.

**Comment by ShrutiArya96** [comment]
I am using this code in js in startGame function  to show to banner on the html page
    banner = new component();
    banner.init(600, 200, "Pictures/banner2.png", 100, 40, "image",1);
But its still not showing

**Comment by ShrutiArya96** [comment]
When I am putting it in the  html code, the banner is getting placed below the canvas not on the canvas.

**Comment by EdwardDunn** [comment]
@ShrutiArya96 Have you created the needed CSS for the banner?

**Comment by EdwardDunn** [comment]
@ShrutiArya96 Closed due to inactivity, please feel free to have a look at other issues in the future.

**Pull request closed without merging**
