### PR TITLE
Created instructions modal

### PR DESCRIPTION
**Pull request by JorgeAndd**
Created instructions modal #44

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@JorgeAndd Couple points before I merge your PR. 

Check your code for the restart button. Works fine when pressed from instructions modal but an error occurs when pressed on game over modal.

The game screen is blank behind the instructions modal, would be better if the game screen is loaded but not started (looks nicer).

Hope this helps!

**Comment by JorgeAndd** [comment]
Sure, I will check.

What error are you getting on game over modal? It is working fine for me

**Comment by EdwardDunn** [comment]
@JorgeAndd The player character moves to the right continuously, it is an intermittent error but occurs frequently.

**Comment by JorgeAndd** [comment]
@EdwardDunn I fixed the background not showing during instructions.

The player moving is an already present bug. If you change your browser tab while moving, for example, the player keeps moving. Maybe create another issue for this one

**Comment by EdwardDunn** [comment]
@JorgeAndd Good spot! Thanks for the contribution, it looks great.

**Pull request merged**
