### PR TITLE
Issue #99 Only one startlevel function left

### PR DESCRIPTION
**Pull request by mordore4**

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@mordore4 Thanks for your contribution, the code is much cleaner now! Would you mind updating your branch to resolve the current conflicts?

**Comment by mordore4** [comment]
There we go, resolved conflicts and tested, still works 100% :)

**Comment by EdwardDunn** [comment]
@mordore4 Really good improvement! 

The only issue I found was that the first level background does not initialise before the instructions modal is displayed. 

This leaves the screen blank behind the modal.

screenshot from 2018-01-08 19-52-07

Thanks for fixing the conflicts.

**Comment by mordore4** [comment]
Woops, fixed that real quick :)

**Comment by EdwardDunn** [comment]
@mordore4 great, thanks!

**Comment by fedeDeb** [comment]
I didn't know where to write, but since I think it's an error due to this change I write here.
The character does not clash with the enemies anymore, or am I wrong?
I was about to add my changes (which I did on the old version of the project) but I realized this.

**Comment by EdwardDunn** [comment]
@mordore4 Apologies, I missed an issue with your PR. The player character is not colliding with the enemy characters. The player can jump on them, but if standing still the enemy just go past.

I have reverted your merge, can you fix the issue and open a new PR?

Thank you @fedeDeb for spotting this!

**Comment by EdwardDunn** [comment]
@mordore4 I have undone the revert for your PR. 

Can you make the correction and open a new PR as soon as possible, thanks!

**Pull request merged**
