### PR TITLE
Added restartButton to main screen

### PR DESCRIPTION
**Pull request by govindbalaji-s**
Fixes Issue #68 
In JS_game.html:
I have added the button for restartgame in buttonWrapper div.
It's onClick is restartGame() .

In Game.js, I have added restartGame() function which stops gameArea and calls startGame(). I have also made space bar to work anytime. Instead of refreshing the page, it now calls restartGame()

### CODE REVIEW

**Comment by govindbalaji-s** [comment]
Except those changes there aren't changes anywhere else. I think the changes includes so much extra lines as changed because of tab vs space inconsistency with my editor?

**Comment by EdwardDunn** [comment]
@govindbalaji-s Sorry about the delay looking at your PR, thanks for your contribution. The restart button works fine but could you position it lower on the screen so that it is separated from the control buttons.

**Comment by govindbalaji-s** [comment]
Will it be good if the restart button is placed next to the level message at the top?

**Comment by EdwardDunn** [comment]
@govindbalaji-s My thought was that it would be best on a new line below the on screen controls. If you want to try it next to the level message we can see what it looks like.

**Comment by govindbalaji-s** [comment]
Sorry was caught up in the school, 
Screenshot
The problem is the game can't be played without zooming out.  I will now make the new commits soon.

**Comment by govindbalaji-s** [comment]
I will try to zoom things out.

**Comment by EdwardDunn** [comment]
@govindbalaji-s The restart button looks good at the top. Can you adjust your CSS, when the window is re-sized the button does not stay fixed. Looks good though!

**Comment by govindbalaji-s** [comment]
I am sorry for the delay. Check this out now.

**Comment by EdwardDunn** [comment]
@govindbalaji-s Thanks for sorting the CSS issue with the restart button. The changes to the control button sizes make it difficult when played on a mobile device. When the screen is shrinked the buttons become very small and difficult to touch. This is the reason their size was fixed. 

The restart button isn't as important for game play, and obviously if it is on the game screen it does need to shrink with the screen size.

Can you set the control buttons sizes back to fixed.

Sorry if this seems trivial but its important to make sure its playable on all devices. Otherwise your work is awesome!

**Comment by govindbalaji-s** [comment]
I am a newbie so I am slow sorry. I have fixed that and now only restart button resizes. the buttonImages class looks a bit unnecessary but I haven't removed them for now incase in future if any css for all button images is needed. If you think they can be removed now, I will do that.

**Comment by EdwardDunn** [comment]
@govindbalaji-s Thanks, works great now! Can you pull down the recent changes to your branch and then push again, i cant merge your branch as it is out of date.

**Comment by govindbalaji-s** [comment]
Thank you for being patient throughout and guiding me.

**Comment by EdwardDunn** [comment]
@govindbalaji-s No problem, thanks for your contribution!

**Pull request merged**
