### PR TITLE
Problem with ubuntu(Issue #17) and main character's jump(Issue#19) solved.

### PR DESCRIPTION
**Pull request by Redarcher9**
Ubuntu's browsers are case sensitive when it comes to read folders.Line number 12,13 and 39 in JS_game.html could not locate the resources because of mismatch in folder names.So i renamed the folders as Pictures(from pictures) and Style-Sheets(from style-sheets)as mentioned in lines 12,13 and 39 of html file.
I have increased the threshold for character's position in order to validate a jump to 170(i.e the main character's position in the window should be more than 170).This will make sure that the charater would jump only when it is close to the ground.I have also reduced the speed of jump to -8 to make the game easier.Everything works fine now.

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@Redarcher9 Awsome work! Well done for fixing the Ubuntu issue. 

I have tried the game with your updated speed and threshold. It works fine but the game has become very difficult. This has highlighted a bigger flaw in the game. Because the enemy characters display at random intervals its means they can appear in large numbers. This makes jumping over all of them impossible. Perhaps a solution to this would be to adjust the for loop that creates enemy characters.
image

Or if you have another solution feel free to give it a try.

**Comment by Redarcher9** [comment]
Why is the loop being iterated 100 times?I assume it will create 100 enemies.But what's the significance of number 100?Because I tried to change it to any number(let's say 50 or 2),the game doesn't works.I get a blank canvas screen

I even tried to put a delay using settimeout so that there is a gap between the x-coordinates of enemy charecter but it gives the same error(gives a blank screen).
Can you suggest something which might work out?

**Comment by EdwardDunn** [comment]
@Redarcher9 The size of the loop is dependant on parts of the updateGameArea function. These loop sizes must also be changed.

**updateGameArea function**

//loop for obstacle collision
for (var i=0; i<100; i++){
	  if (myGamePiece.crashWith(myObstacles[i])) {
        myGameArea.stop();
        GameOver();
	    }
} 

//obstacle update
	for (var i=0; i<100; i++){
	myObstacles[i].update();
        }

//loop to set speed of obstacles
	for (var i=0; i<100; i++){
	myObstacles[i].x += -2;
	} 

**Hope this helps!**

**Comment by EdwardDunn** [comment]
@Redarcher9 Hey, would you mind submitting a new PR with just the file name changes you made to solve the Ubuntu issue? I think a couple of people have encountered this issue so would be good to get it solved on the master branch.

Might be a good idea to update your branch first because there has been a few additions.

Thanks!

**Pull request closed without merging**
