### PR TITLE
Game title, 'The Jumping Dead' is added to the instruction modal.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@rurangana Thanks for the contribution!

Your title is good but would you mind making it a little more exciting? Maybe add some graphics to it?

Let me know if you need any help.

**Comment by ghost** [comment]
I'm very sorry for the late reply. Graphics means, should it be modified as a JPEG with more than just font-styling?

**Comment by EdwardDunn** [comment]
@rurangana Yeah thats a good idea!

**Comment by EdwardDunn** [comment]
@rurangana I am closing the PR as another user is looking to create a banner. Feel free to contribute again with any new issues, thanks!

**Pull request closed without merging**
