### PR TITLE
Added one point in instructions.

### PR DESCRIPTION
**Pull request by asas2016SEC**
Added a logo for the game.

### CODE REVIEW

**Comment by AanjaneyaSinghDhoni** [comment]
Added a logo.

**Comment by EdwardDunn** [comment]
@AanjaneyaSinghDhoni Thanks for your contribution, looks cool!

Just a couple things;

- The logos resolution is little low so it appears blurry
- The right side cuts off a bit early
- Could you place it in the Pictures folder

screenshot from 2018-01-18 19-20-06

Hope this helps!

**Comment by asas2016SEC** [comment]
okay, consider it done.

**Comment by asas2016SEC** [comment]
i corrected the logo please have a look and tell.

**Comment by EdwardDunn** [comment]
@AanjaneyaSinghDhoni The logo does not appear now. 

Replace line 63 with the following code;

img src="Pictures\logo.png" width="100%" height="10%" align="middle"

You only need to place it in the Pictures folder, not a drive.

Its important that you test any changes before committing them as that would have highlighted this issue to you.

**Comment by EdwardDunn** [comment]
@AanjaneyaSinghDhoni Closed due to inactivity, please feel free to look at other issues in the future.

**Pull request closed without merging**
