### PR TITLE
Added new level issue #27

### PR DESCRIPTION
**Pull request by brissettdwayne**

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@brissettdwayne Thanks for the contribution! Just a couple things before I merge it.

- The background used doesn't work for the game, because the characters float in the air rather than on a platform
- Can you update the Copyrights.txt file for new images added
- There is an error in your if statement
    if else(currentLevel === 3){
      startLevel3();
    }

should be 'else if' 

Hope this helps!

**Comment by brissettdwayne** [comment]
I submitted the changes. Sorry it took a while.

**Comment by EdwardDunn** [comment]
@brissettdwayne Hey, thanks for updating your PR. The new background has the same problem, the characters are floating in the middle of the screen. If you look at the first two levels they have a straight floor that the characters sit on. You can solves this by adjusting your image and changing the characters position on the screen. I found it is best to choose a background with a straight floor area for the character.

Like this,

capture


Hope this helps!

**Comment by brissettdwayne** [comment]
I resubmitted changes to the code!

**Comment by kyxap** [comment]
@brissettdwayne do not forget to resolve conflicts:

**Comment by brissettdwayne** [comment]
I resolved the conflict

**Comment by EdwardDunn** [comment]
@brissettdwayne Great, it works well!

**Pull request merged**
