### PR TITLE
High Score Saved

### PR DESCRIPTION
**Pull request by Samuel-Pedraza**
This enables high score to be saved between games played. If you close out of the browser, and log back in, you can still save your highest score.

If we don't want to use localstorage for this, I can set a cookie for this instead. It can still be decrypted, since the key would be in Game.js, but it would make it more difficult for the player to change the high score.

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@Samuel-Pedraza Great idea!

There is however an error in that the player character no longer appears. Can you have a look at that?

**Comment by Samuel-Pedraza** [comment]
@EdwardDunn It looks like there was a merge conflict. I went ahead and fixed it, and it should be good to go now.

**Comment by EdwardDunn** [comment]
@Samuel-Pedraza Thanks for looking at that. Would you mind pulling down the most recent changes before I merge.

**Comment by Samuel-Pedraza** [comment]
@EdwardDunn Should be good to go!

**Comment by EdwardDunn** [comment]
@Samuel-Pedraza The issue has been resolved by @Germlord. Thank you for taking the time to look at this.

**Pull request closed without merging**
