### PR TITLE
Stop music and Pause Buttons #104

### PR DESCRIPTION
**Pull request by fedeDeb**
Added Pause and Mute Button on screen, modified css.

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@fedeDeb Hey, i am waiting on mordore4 fixing the issue you noticed (thanks for letting me know) before merging any new PRs. 

As soon as its done i will look at this for you.

**Comment by EdwardDunn** [comment]
@fedeDeb Good additions!

I found a couple issues in testing, the buttons overlap when the screen size if reduced.

screenshot from 2018-01-10 19-03-34

Also the buttons work in Chrome but not in FireFox. This is mostly likely because of invalid HTML that Chrome will render but FireFox wont.

**Comment by fedeDeb** [comment]
Done :)

**Comment by EdwardDunn** [comment]
@fedeDeb Thanks for sorting that.

The layout still needs a bit of work when the screen resizes.

screenshot from 2018-01-11 13-59-59

The Mute and Pause buttons would be better moving down together as it looks a bit messy when one is in a different place to the other. 

A good thing to do when testing is to slowly reduce the screen size and see how the buttons layout changes. This much more important these days with people playing on devices of all different sizes.

Hope this helps!

**Comment by fedeDeb** [comment]
I've tried to reduce slowly the screen size, now mute and pause buttons move down together!

**Comment by EdwardDunn** [comment]
@fedeDeb Thanks for changing that. The buttons are a great addition!

**Pull request merged**
