### PR TITLE
Update mute button and added duck button

### PR DESCRIPTION
**Pull request by Booxworm**

### CODE REVIEW

**Comment by Booxworm** [comment]
Sorry didnt really know how the pull requests worked and stuff, so i deleted the forked persion perviously

**Comment by Booxworm** [comment]
Added duck button into the game.

Clicking it makes the character disappear though. I wasnt sure how to fix it, but i'll try and look into it somemore

**Comment by EdwardDunn** [comment]
@Booxworm Ok great. The mute for the settings button works good though. Let me know when you have the 'duck button working, or leave a message if you need any help.

**Comment by Booxworm** [comment]
Yeap got it to work, should be good to merge!

**Comment by EdwardDunn** [comment]
@Booxworm Great work! Thanks for your contribution.

**Pull request merged**
