### PR TITLE
Added Enemy Killed Sound Effect

### PR DESCRIPTION
**Pull request by tata81**
#82 
1. Added source of the sound clip when enemy is killed in copyright.txt file.
2. Added audio element in the index.html
3. Audio file named enemy_killed.wav added in audios folder.
4. Added condition in the updateGameArea function in game.js file.

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@tata81 Sorry I haven't looked at your PR yet, we are having an issue we a merge conflict from a previous PR. I will get back to you in a couple days.

**Comment by EdwardDunn** [comment]
@tata81 Thanks for waiting for us to resolve the issue we were having.You PR looks good, would you mind pulling down the most recent changes to resolve the conflicts on your branch? I will then merge it into master.

**Comment by tata81** [comment]
Hi @EdwardDunn  Thanks for you time for patiently checking out my PR and helping me out in the process.
As guided I have pulled down the most recent changes and resolved the conflicts. Please checkout out and let me know you thoughts. Thanks

**Comment by EdwardDunn** [comment]
@tata81 Thanks for resolving the conflicts.

Great work!

**Pull request merged**
