### PR TITLE
Fixed issue resulting from merge conflicts

### PR DESCRIPTION
**Pull request by Germlord**
It seems that the pull request adding in a level transition modal did not properly resolve merge conflicts--I found Git code still present in the game file. I resolved the changes, which I have tested with my local version and found all new features to be implemented properly. The only other change I made was removing an argument from the resumeGame() function, which didn't appear to actually use the levelTransitionModal variable before updating it.

### CODE REVIEW

**Comment by Germlord** [comment]
UPDATE: In light of the recent couple of issues, I added a section on how to properly resolve conflicts when merging upstream changes. Hopefully it will help avoid these kinds of problems in the future--do please give it a read though, I would like to be sure that what I wrote is correct.

**Comment by EdwardDunn** [comment]
@Germlord Thank you for resolving that, I didn't realize it was a merge conflict from #158.

**Comment by EdwardDunn** [comment]
@Germlord There is still an issue with the player character not appearing in the first level. I thought this might have been an issue on my local machine as it was happening in all branches but it is still occurring in the github.io page. Sorry i'm mega busy just now so not getting much chance to look at what is causing the problems.

**Comment by Germlord** [comment]
Weird. Well, I’ll be working on the game for a couple hours today, so I’ll get whatever the problem is handled.

**Comment by Germlord** [comment]
@EdwardDunn okay, well, I updated my local files to be exactly even with yours. And my files run fine--it's missing the music in Firefox, but it doesn't have the issue of failing to create Components that the github.io version seems to have. That version seems like it runs fine for a while if you restart...and then all the Component objects will just disapper. How exactly do you run your local version? I run my local index file in Google Chrome.

I'll keep working on this, but I'm not sure where to even look for a problem like this.

**Comment by EdwardDunn** [comment]
@Germlord I also run my index file in chrome. Thanks for looking into it. Yeah it's a really difficult bug to find. If u can't resolve it I will revert the commits back to the last working copy.

**Comment by Germlord** [comment]
@EdwardDunn alright, I'm pretty sure I've located the problem! Someone advised me to run the game along with the console, and the console reported that it couldn't call upon the "Zombie" image! This would explain why the issue only occurs in the first level. In addition, I was also able to reproduce this issue by simply removing the "Zombie" image from my version of the game.

I think this occured because I capitalized my version of the "Zombie" image name, whereas it looks like the one on your Github page is written as "zombie". So this could be a simple matter of case sensitivity. I'm sending a Pull Request your way where I revert the "Zombie" name back to lowercase for both the picture and game.js file, and we can see if that fixes the problem.

**Pull request merged**
