### PR TITLE
Create Level 5 #51

### PR DESCRIPTION
**Pull request by fedeDeb**
I created level 5, inserting two new enemies, a new character and a new location. I have included in the code comments that briefly explain the changes made.

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@fedeDeb Thanks for submitting your pull request, the new images and the use of enemies coming from the left if excellent! 

The only one issue i had when testing it was that the player character would often immediately hit an enemy coming from the left when the level loads. Could you adjust the position the player character (perhaps to the middle of the screen instead of starting at the left) to avoid this?


Really looks good though, the comment in your for loop is very clear and will aid other contributors. Well done!

**Comment by fedeDeb** [comment]
Done :)

**Comment by EdwardDunn** [comment]
@fedeDeb Great! Well done the new level is really good.

**Comment by fedeDeb** [comment]
Thank you :)

**Pull request merged**
