### PR TITLE
Large formatting changes; bug fixes and optimizations

### PR DESCRIPTION
**Pull request by Germlord**
Don't panic, most of this change is whitespace. Here's an in-depth summary of the changes:

-Added ESLint file which highlights formatting, style, and other issues, for people that have the necessary stuff downloaded. It should have no effect on systems that don't.
-Made a LOT of minor style fixes according to the ESLing standards.
-Tweaked moveUp for when the player stomps on an enemy to be more noticeable/satisfying.
-Added if statement to moveUp so that if a player stomps on an enemy while not moving down quickly, the stomp-jump effect would still be noticeable.
-Changed variable “z” to “flyCounter” to improve readability.
-Changed time display calculation to use a Math.Ceil() formula, so that the display would better match intuition (i.e. it starts at 30, doesn’t hit 0 until time runs out entirely.
-Removed unused moveDown() function.
-Removed unused startGameElements() function.
-Added back in duck capabilities that had been removed when settings were added.

_______________________________________________________________________________________________________________

There seem to still be some bugs resulting from adding the settings that I didn't fix (mostly making sure that ducking is properly accounted for), but all in all everything seems to be working well in my local version.

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@Germlord oh sorry i didn't realize the duck feature wasn't working when I tested the new settings feature, thanks!

The ESLint file is a good addition.

Would you mind resolving the conflicts before I merge?

**Comment by Germlord** [comment]
Of course. I’ll get things updated and sent in a new version tonight.

**Comment by Germlord** [comment]
@EdwardDunn okay, things should be all ready to merge. As usual, here's the full list of changes for the latest merge.

-Renamed gameOptions to displayOptionsModal, and optionsGame() to gameOptions(), for easier reading.

-Added behavior so that accessing Settings would pause the game, and leaving it would unpause it. It's slightly crude, but seems to be effective.

-Made jumping and ducking mutually exclusive, so that we couldn’t do weird duck-jumps.

-Added DOWN options to the Settings menu.

**Comment by EdwardDunn** [comment]
@Germlord Thanks, those are good additions.

**Pull request merged**
