### PR TITLE
Added new enemy obstacles

### PR DESCRIPTION
**Pull request by treyhboy**
screenshot-2017-9-27 platform game 2
screenshot-2017-9-27 platform game
screenshot-2017-9-27 platform game 1
solved issues
#30 
#6 
Changes Made
->I have added new jumping bird enemy to increase the difficulty of the game
->Changed the collision range between enemy and player
->Solved some syntax error 
hope you like the changes

### CODE REVIEW

**Comment by EdwardDunn** [comment]
@treyhboy Awesome work! The jumping birds is a great idea to add some complexity to the game. Would you mind adding a few comments in for the code you added, this just helps new contributors understand the code more easily. If you could pull down some recent changes to resolve the conflict on your branch, then I will merge your PR. 

Really great work!

**Comment by treyhboy** [comment]
Cleared the conflict and added some more comments 
i think we are good to go :)

**Comment by EdwardDunn** [comment]
@treyhboy One of the additions you have made has caused an error, the game screen is appearing blank.

**Comment by treyhboy** [comment]
Solved the error @EdwardDunn 
Apology for the mistake

**Comment by EdwardDunn** [comment]
@treyhboy Great thanks!

**Pull request merged**
